language: php
php:
- 7.2
sudo: false
env:
  global:
  - PLUGIN_NAME=TinectOptimusOptimizer
cache:
  directories:
  - "${HOME}/.composer/cache/files"
install:
- composer install
script:
- "./build.sh $TRAVIS_TAG"
deploy:
  provider: releases
  api_key:
    secure: tKluq6DuOYx+J6IVu31EyBTQDWDNZg7636r/v++WstWqUgh1fCXP3+88IspCkp4NxUJ/CumW9MiiUPxjeRcmPoZjqcRLpJiHjZ2wlI1Siig0/tKT38dYIvFJL+an+076geNK95aMUAnoGtA3ylOBRM9Ss+L/ZCxDUYH+WQ1OBAXcIP7arA73l4RtD/Uf/QdfeHcUBPLgo0tvYxAqSpogGYCs+0EfG7HslpCwCRZHpIujpOICfDK1aBrNwFbBwemdwpa1nn9HQCYNBiL8ZS3k5jWHO0Z8y5NTcC3ZyGqEnyZ6C36sOfMx6Cfw69Pg4EpP1Z90ecBX4kfYESNB1BoZ44jX2fuLw1vfwxbjptNWJASpLPS4g4dCtz6Ew7RxIqPJ6OpgfW8RWvcco2fFi3IpnXt5bUOcaQUeTzAb2NySP7xLtPuZmqx/l6MDOydWAUqbCMwRo7IxG8KUB8oo4BzSI4QmYHG4Q/TChn90/FXY3kIFUV5+kPMfiWKbY3Kr5svFPdPvaYuMt++mOLffgTOI1XXibmVKPpbm0pbHhI+VDs388J5595r+TC5aj+LAYakkGzgaBblx1oownzAbIct4DiaE5J0C+iU9xPf3R+6KtTDI72tLiuUNfXCCVQ9TAsnfOeeeTAxP8o/QLToufSPpphbZdd74W/L6XwG0sCg405U=
  file_glob: true
  file: TinectOptimusOptimizer*.zip
  skip_cleanup: true
  on:
    repo: tinect/TinectOptimusOptimizer
    tags: true
